name: 'Deployment'

on:
  push:
    branches: [main]

jobs:
  tests: 
    name: Deploy
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

        
      - name: Set up Go Toolchain
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.0'

      - name: Install Goose
        run: go install github.com/pressly/goose/v3/cmd/goose@latest

      - name: Migrate DB
        run: scripts/migrateup.sh

      - name: Run Production Build Script
        run: scripts/buildprod.sh
