name: ci
on: 
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      
      - name: Set up Golang
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.0'
        
      - name: Run tests
        run: go test --cover ./...
      
  style: 
    name: Styles
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      
      - name: Set up Golang
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.0'
      
      - name: Fmt code
        run: test -z $(go fmt ./...)